#! /hint/sh

case $HOME in "$PWD") ;; *) return; esac 
[ -d ~/.mozilla ] || return


unalias _find_ || :
. "${B?}"/_loadable/_find_.sh_

(


puts 'anti-homedir-firefox: removing...' >&2
sleep 3
#command. _find_ || . "${B?}"/_loadable/_find_.sh
cd "${HOME:?}" || exit
{
	echo
	date -Im
	i=$(_find_ .mozilla | tee-fd 3 | wc -l)
} >>~/.cache/0/.mozilla_find 3>&1

case $i in [0-9][0-9][0-9][0-9])
	puts >&2 "Not expected to get that many files '$i' in output from \`find .mozilla\`"
	return
esac
rm -rfv .mozilla/


) >&2
