#! /hint/sh


case $- in *i*)
	if [ -d /~ ]; then 
		fn() {
			local HOME 2>&-
			HOME=/~ . "${B:=/~/.config/bash/bashrc.d}"/_main
		}
		fn
		unset -f fn
	else
		. "${B:=/~/.config/bash/bashrc.d}"/_main
	fi
esac
