#! /hint/sh


case $HOSTNAME in
dumpling|op5)
	B=${B:-"$HOME/B"}
esac

. "${B:?}"/_main

return

#elif [ -d /~ ]; then 
#B=/~/.config/bash/bashrc.d

case $- in *i*)
	if [ -d /~ ]; then 
		fn() {
			local HOME 2>&- || return
			HOME=/~ . "$B"/_main
		}
		fn
		unset -f fn
	else
		. "${B:=/~/.config/bash/bashrc.d}"/_main
	fi
esac
