#! /hint/sh

alias \
	i='unset i' \
	echo-1l='printf %s\\n' \
	command.='command >/dev/null -v' \
	\
	fori='for i in' fori{{='for i;{{' '{{=do' '}}=done' \
	loop='while :;' pool='do :;done' elihw='do :;done' 'loop{{=while :;{{' \
	and='(exit $?)&&' or='(exit $?)||' \
;

command. local     || . ~/B/%local.fallback
command. com-which || . ~/B/%com-which.fallback

if case $- in
	-|'')
		case $PS1 in
			'') false;;
			*) true;;
		esac
	;;
	*i*) true;;
	*) false;;
esac; then
	shell_is_interactive=''
else
	unset shell_is_interactive
fi


# if ( i=_; : "${!i}" ) 2>/dev/null 1>/dev/null; then
case $sh_is in
	bash|zsh)   shuf_1() { i=$(( ( ${RANDOM:?} % $# ) + 1 )); echo-1l "${!i}"; i; };;
	ash|bb_ash) shuf_1() { eval "( echo-1l \"\${$(( ( ${${RANDOM:?} % $# ) + 1 ))}\" )"; };;
	*)          shuf_1() { eval "( echo-1l \"\${$(( ( $$            % $# ) + 1 ))}\" )"; };;
esac

# GNUtector detect if GNU coreutils options are supported
unset os_gnu os_an os_busybox os_toybox
case ${OSTYPE:-$(uname -o)} in
	linux-gnu|GNU/Linux)   os_gnu='';; # check for GNU+Busybox is not important for now
	linux-android|Android) os_an='';; # Termux? but it could be busybox toybox termux or any other shell app ..
	# TODO windows
	linux-musl|Linux) # Alpine, KISS
		i=$(command -v ls)
		case $i in # note: this will fail if ls is alias or fn
			ls) os_bb='';; # applet is build in
			*/ls) false;;
			*)
			echo-1l >&2 \
				"~/B/_core: got unexpected output" \
				"~/B/_core: \$ command -v ls -> $i" \
				"~/B/_core: \$?:$?" \
			;
			return 1
		esac || { [ -L "$i" ] && os_bb=''; } || {
			i=$(readlink -- "$i" 2>/dev/null)
			case $?:$i in
				0:*/busybox|busybox) os_bb='';;
				0:*/toybox|toybox) os_bb=''; os_toybox='';;
				*)
				echo-1l >&2 \
					"~/B/_core: well idk then what this OS this is, 'ls' seems to not be a symlink" \
					"~/B/_core: \$ readlink -- \$(command -v ls) -> $i" \
					"~/B/_core: \$?:$?" \
				;	
				return 1
			esac
		}
	;;
	*) echo-1l >&2 "~/B/_core: cannot detect current os GNU/(Busybox+Musl)/Android"; return 1;;
esac
i

return

#command_fn() { # never used , uncomment when needed
#  # type "$1" 2>/dev/null | grep -qe function\$ # POSIX
#  # [[ `type -- "$1" 2>/dev/null` = *\ function ]] # bashism
#  # WARING: tested in (bash,zsh,dash,ksh,yash), test more?
#  
#  case "$(command -V -- "$1" 2>/dev/null | head -n 1)" in
#  (*\ function) return 0;;
#  (*) return 1;
#  esac
#}
#

# shuf_1(){
	# eval "printf %s\\n \"\${10}\""
	# eval "printf %s\\n \"\${$(( ( ${RANDOM:-1$(\dd if=/dev/urandom count=3 2>&- | tr -d -c '0-9' | head -c 10)} % $# ) + 1 ))}\""
	# shift "$(( ${RANDOM:-1$(\dd if=/dev/urandom count=8 bs=1000 2>&- | tr -d -c '0-9' | head -c 10)} % $# ))"
	# printf %s\\n "$1"
# }
#bash shuf:


_tr_s(){ ( set -f; IFS=$1; set -- $(cat); IFS=$2; printf %s\\n "$*"; ); }
# command. env: || alias env:='IFS="${PATHseparator:-":"}" var_1l'

# alias alias--='alias 2>&- --' # was used only 1 and now no mire since `alias cd-='cd -' -='cd -'`
