#! /hint/sh
alias \
	ii='{ case ${i+x} in      x) puts "warning: ${FUNCNAME+"(in fn $FUNCNAME)"} ${BASH_SOURCE+"(in file $BASH_SOURCE +$BASH_LINENO )"} i is defined with value: $i"        >&2; esac; }' \
	i='{ ii; unset i; }' \
	I='{ case ${i+x} in x) ;; *) puts "warning: ${FUNCNAME+"(in fn $FUNCNAME)"} ${BASH_SOURCE+"(in file $BASH_SOURCE +$BASH_LINENO )"} i was not defined but unset was requested" >&2; esac }; unset i' \
	i{='i' }i='I' \
	\
	puts='printf %s\\n' \
	command.='command >/dev/null -v' \
	\
	fori='for i in' fori{{='for i;{{' '{{=do' '}}=done' \
	loop='while :;' pool='do :;done' elihw='do :;done' 'loop{{=while :;{{' \
	and='(exit $?)&&' or='(exit $?)||' \
;

. ~/B/_fallback/_fallback

case $- in
	-|'')
		case $PS1 in
		'') unset shell_is_interactive;;
		*) shell_is_interactive='';;
		esac
	;;
	*i*) shell_is_interactive='';;
	*) unset shell_is_interactive;;
esac

# if ( i=_; : "${!i}" ) 2>/dev/null 1>/dev/null; then
case $sh_is in
	bash|zsh)  shuf_1_toi() { i=$(( ( ${RANDOM:?}   % $# ) + 1 )); i="${!i}"; unset shuf_1_ind; };;
	*)         shuf_1_toi() { i=$(( ( ${RANDOM:-$$} % $# ) + 1 )); eval "i=\"\${${i}}\""; unset shuf_1_ind; };; # "$$" still got for 1 time usage
esac

# GNUtector detect if GNU coreutils options are supported
unset os_gnu os_an os_busybox os_toybox os_win
case ${OSTYPE:-$(uname -o)} in
	linux-gnu|GNU/Linux)   os_gnu='';; # check for GNU+Busybox is not important for now
	linux-android|Android) os_an='';; # Termux? but it could be busybox toybox termux or any other shell app ..
	MS/Windows) os_win='';;
	linux-musl|Linux) # Alpine, KISS
		i{
		i=$(command -v ls)
		case $i in # note: this will fail if ls is alias or fn
			ls) os_bb='';; # applet is build in
			*/ls) false;;
			*)
			puts >&2 \
				"~/B/_core: got unexpected output" \
				"~/B/_core: \$ command -v ls -> $i" \
				"~/B/_core: \$?:$?" \
			;
			return 1
		esac || { [ -L "$i" ] && os_bb=''; } || {
			i=$(readlink -- "$i" 2>/dev/null)
			case $?:$i in
				0:*/busybox|busybox) os_bb='';;
				0:*/toybox|toybox) os_bb=''; os_toybox='';;
				*)
				puts >&2 \
					"~/B/_core: well idk then what this OS this is, 'ls' seems to not be a symlink" \
					"~/B/_core: \$ readlink -- \$(command -v ls) -> $i" \
					"~/B/_core: \$?:$?" \
				;	
				return 1
			esac
		}i
		}
	;;
	*) puts >&2 "~/B/_core: cannot detect current os ${OSTYPE:-$(uname -o)} in GNU || (Busybox+Musl) || Android || WINDOWS"; return 1;;
esac



return

#command_fn() { # never used , uncomment when needed
#  # type "$1" 2>/dev/null | grep -qe function\$ # POSIX
#  # [[ `type -- "$1" 2>/dev/null` = *\ function ]] # bashism
#  # WARING: tested in (bash,zsh,dash,ksh,yash), test more?
#  
#  case "$(command -V -- "$1" 2>/dev/null | head -n 1)" in
#  (*\ function) return 0;;
#  (*) return 1;
#  esac
#}
#

# shuf_1(){
	# eval "printf %s\\n \"\${10}\""
	# eval "printf %s\\n \"\${$(( ( ${RANDOM:-1$(\dd if=/dev/urandom count=3 2>&- | tr -d -c '0-9' | head -c 10)} % $# ) + 1 ))}\""
	# shift "$(( ${RANDOM:-1$(\dd if=/dev/urandom count=8 bs=1000 2>&- | tr -d -c '0-9' | head -c 10)} % $# ))"
	# printf %s\\n "$1"
# }
#bash shuf:


_tr_s(){ ( set -f; IFS=$1; set -- $(cat); IFS=$2; printf %s\\n "$*"; ); }
# command. env: || alias env:='IFS="${PATHseparator:-":"}" var_1l'

# alias alias--='alias 2>&- --' # was used only 1 and now no mire since `alias cd-='cd -' -='cd -'`
