#! /hint/sh

: "
${HOSTNAME:=$(hostname)}
${OLDPWD=$HOME/.local}
"

export \
GIT_DIR \
BAT_PAGER="less -RF" \
BAT_CONFIG_PATH=/etc/bat.conf \
PASSWORD_STORE_DIR=~/0/GG/pass/ \
TERMINAL=konsole \
KISS_PATH=~/0/gh/denisde4ev/repo/personal \
XKB_DEFAULT_LAYOUT='us(carpalx)' \
\
PATHseparator=: \
PATHSEP=/ \
\
NEW_LINE='
' \
TAB_CHAR='	' \
;

alias command.='command >/dev/null -v'

if command. most; then
	export PAGER=most
	if command. bat; then
		export MANPAGER="sh -c 'col -bx | bat -l man -p'"
	elif command. less; then
		export MANPAGER="less"
	fi
else
	if command. bat; then
		export MANPAGER="sh -c 'col -bx | bat -l man -p'"
	fi
	if command. less; then
		export PAGER="less"
	fi
fi
# : "${NEW_LINE:=$'\n'}"


# XKB_DEFAULT_LAYOUT -> for river WM # https://github.com/ifreund/river/issues/254
# MOZ_USE_XINPUT2=1  -> firefox support touchscreen # I put in in /etc/environment

# PATHSEP='/'        -> a path separator used in mine scripts, for busybox-w32.sh is PATHSEP='/\'
# # PATHseparator=$( PATH=1:2 ; printf %c "${PATH#1}" ) # expected Windows to use ';'



case $TERM in
*xterm*)       export EDITOR=${EDITOR-micro};;
linux|screen*) export EDITOR=${EDITOR-nano};;
*)             export EDITOR=${EDITOR-micro};;
esac

	

# note $new_line is from "$B"/_core

# some enviromnent aliases, (for now all are for PAGER var fix)
alias \
su='PAGER= MANPAGER= \su' \
doas='PAGER= MANPAGER= \sudo -S ' \
sudo='PAGER= MANPAGER= \doas ' \
9='PAGER= MANPAGER=less \9 ' \
gh='PAGER=less \gh' \
HELP='MANPAGER=most \HELP' \
systemctl='PAGER= systemctl' \
;
# git='PAGER=less \git' \ moved to "$B"/_loadable/git.sh
