#!/ /hint/sh

# unalias -a # for now not a problem

. ~/B/_env
. ~/B/_PATH
. ~/B/_core
# big dot / "BULLET" (U+2022) -> alias •=source._all :
. ~/B/_U+2022•
# shoud NOT start [_.%] or end [%~] :
•  ~/B/[!_.%]*[!%~] ~/B/[!_.%~]

{
# case $- in *c*|*x*)false;; *);; esac  || # bash only ...

# if is in '$' command OR if xtrace(set -x) is on
# [ $# -eq 0 ] && [ -z "$({ :; } 2>&1)" ] || return 0
case $#:$({ :; } 2>&1) in
	0:) ;;
	*) return 0;;
esac
}

# TODO: but what if is not in .config ? and then we have no $XDG_CONFIG_HOME ..
#  check what wiki says in this case.
[ -e ~/.config/user-dirs.dirs ] && • ~/B/_home

sh=''
case ${0##*/} in
	bash|rbash|-bash) • ~/B/%[!_.%]*.bash; . ~/B/_fetch/_fetch >&2 0<&-;;
	zsh|-zsh)         • ~/B/%[!_.%]*.zsh;  . ~/B/_fetch/_fetch >&2 0<&-;;
	dash|-dash)       • ~/B/%[!_.%]*.dash; . ~/B/_fetch/_fetch.sh >&2 0<&-;;
	ash|-ash)         • ~/B/%[!_.%]*.ash;  . ~/B/_fetch/_fetch.sh >&2 0<&-;;
	_main)
		echo-1l >&2 'shell not be detected, $0 is _main'
		case ${BASH:-${ZSH:-x}} in
			$BASH) • ~/B/%[!_.%]*.bash; . ~/B/_fetch/_fetch >&2 0<&-;;
			$ZSH)  • ~/B/%[!_.%]*.zsh;  . ~/B/_fetch/_fetch >&2 0<&-;;
			*)     • ~/B/%[!_.%]*.sh;   . ~/B/_fetch/_fetch.sh >&2 0<&-;;
		esac
	;;
	sh|-sh|mksh|-mksh) • ~/B/%[!_.%]*.sh; . ~/B/_fetch/_fetch.sh >&2 0<&-;;
	*)
		echo-1l >&2 'unrecognized shell, assuming sh'
		• ~/B/%[!_.%]*.sh; . ~/B/_fetch/_fetch.sh >&2 0<&-
	;;
esac

return 0
