#! /hint/bash

case :${PATH:?}: in *:${HOME:?}/bin/@op5t-termux:*|::) return; esac

PATH=\
$HOME/.local/bin/_/bins-trap:\
$HOME/.local/bin/HOME-disallowed.d:\
\
$HOME/.local/bin/home:\
\
$HOME/.local/bin:\
$HOME/.local/bin-external:\
${os_gnu+$HOME/.local/bin/bin.bash:}\
\
$PATH${PATH:+:}\
\
$HOME/.local/bin/songs:\
$HOME/.local/bin/node:\
\
$HOME/.local/bin/@/chroots:\
$HOME/.local/bin/@/ssh\
${SSH_CLIENT:+":$HOME/.local/bin/ssh-client"}\
;

