#! /hint/bash

case :${PATH:?}: in *:${HOME:?}/bin/@op5t-termux:*|::) return; esac

PATH=\
$HOME/bin/_/bins-trap:\
$HOME/bin/HOME-disallowed.d:\
\
$HOME/bin/home:\
\
$HOME/bin:\
$HOME/.local/bin:\
${os_gnu+$HOME/bin/bin.bash:}\
\
$PATH${PATH:+:}\
\
$HOME/bin/songs:\
$HOME/bin/node:\
\
$HOME/bin/@/chroots:\
$HOME/bin/@/ssh\
${SSH_CLIENT:+":$HOME/bin/ssh-client"}\
;

