#! /hint/bash

# case :$PATH: in *:$HOME/bin/@op5t-termux:*) return;esac
PATH=\
~/bin/_/bins-trap:\
~/bin/HOME-disallowed.d:\
\
~/bin/home:\
\
~/bin:\
~/.bin:\
${os_gnu+~/bin/bin.bash:}\
~/.bin/local:\
"$PATH${PATH:+:}"\
~/bin/songs:\
~/bin/node:\
~/bin/@op5t-termux
