#!/ /hint/sh


##speedtest='speedtest --bytes' \
#old: whatislove='printf "What is love?\\nOh baby, don\\x27t hurt me\\nDon\\x27t hurt me\\nNo more...\\n"' \

case $TERM in
	screen-*) ;;
	*) alias xmrig='byobu new sudo xmrig';;
esac

alias \
bAt='bat -A' \
cut='cut -d " " -f' \
mv++='/~arcowo/bin/_/mvpp/mv++' \
CCCCCCC='sudo loadkeys carpalx; setxkbmap "us(carpalx)"' \
IFS='set -f; IFS="$new_line"' \
bash-debugger-start='debugger=1 bash-debugger' \
argv='(arg "$@")' \
minecraft-1.12.2='/~arcowo/0/game/MC/1.12.2/start' minecraft-1.16.5='/~arcowo/0/game/MC/1.16.5/start' \
fd.err='>&2 '  fd.to2='>&2 '  fd.out='>&1 '  fd.to1='>&1 '  fd.swap='3>&2 2>&1 1>&3 '  fd.copy-err='tee /dev/stderr' \
whatislove='( printf "What is love?\\nOh baby, don\\x27t hurt me\\n"; printf "Don\\x27t hurt me\\n" >&2; printf "No more...\\n" )' \
foo='echo bar' \
mongod='\mongod --logpath /dev/stdout' \
mktmp=mktemp \
cd.mktemp='cd "$(mktemp -d)"' \
\
quote-this='printf %s\\n \!#:q' \
quote='printf "%q\\n"' \
nbsp='printf \\uA0\\n' \
'-=echo ' \
'?-=quote ' \
'?-1l=echo-1l ' \
'R!=history -r' \
'S!=sudo \$ "$(history -p \!\!)"' \
'D!=doas \$ "$(history -p \!\!)"' \
'C!=printf %s "$(history -p \!\!)" | cin' \
'CC!=printf %s "$(history -p \!:q)" | cin' \
\
grep='\grep --color=auto' \
egrep='\egrep --color=auto' \
pgrep='\pgrep --color=auto' \
diff='\diff --color=auto' \
diff-arch='diff --unified --recursive --text'   path='echo-1l "$PATH" | tr "${PATHseparator:-":"}" \\n' \
pacman-diffs='(find /etc 2>/dev/null -name "*.pacnew" -mtime -360 -type f | sed "s/.pacnew\$//")' \
micro-diff='\micro-diff --color=auto' \
\
mkd=mkdir \
mv='\mv -vi' cp='\cp -vi' rm='\rm -v' ln='\ln -vi' chmod='\chmod -v' readlink='\readlink -v' umount='umount -v' mv-ln='\mv-ln -vi -r' \
mount='\mount -v' chown='\chown -v' rmt='rmtrash -Iv' \
mvT='mv -T' cpT='cp -T' lnT='ln -T' \
\
Iown='chown "${UID:-"$(id -u)"}:${GROUPSB-"$(id -g)"}"' \
RootOwns='chmod root:root' \
Iown.ug=Iown \
Iown.u='chown "${UID:-"$(id -u)"}"' \
Iown.g='chown "${UID:-"$(id -u)"}:${GROUPSB-"$(id -g)"}"' \
777='chmod 777' 755='chmod 755' \
1.1='ping 1.1' \
\
192.grep='ip route get 1 | grep -C 1000 "192\\.168\\.[0-9]*\\.[0-9]*"' \
ping='\ping -c 128' \
myip='echo-1l "$(curl -s ipinfo.io/ip)"' \
wc='\wc -l' \
rsync='\rsync -azvhP' \
fuserumount='fusermount -u' \
tb="nc termbin.com 9999" \
sync='time \sync' \
s='sudo ' sudo@kiss='sudo @kiss' \
\
sshd='"$(which \sshd) -p 8022 -d -f ~/.ssh/sshd/sshd_config -h ~/.ssh/sshd/ssh_host_ed25519_key"' \
git-ssh-deni2020='GIT_SSH_COMMAND="ssh -i ~/0/GH/deni2020/.ssh/id_ed25519" git push' \
minicom='\minicom -m -c on -D unix#/tmp/ttyS0' \
\
sed-windows-new-line='sed s/\$/\\r/' \
sed-trim-space-end='sed -E s/\\s+\$//' \
shellcheck.which='cmd-which -c shellcheck' \
\
df='\df -h' \
free='\free -mt' \
rm.pacmanlock='rm /var/lib/pacman/db.lck' \
netstat='\netstat -tulpn' \
ll.which='cmd-which -c "\$ ll"' \
\
\
userlist='cut -d: -f1 /etc/passwd' \
update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
pactree='\pactree --color' \
\
adb-kill-server='adb kill-server' \
\
fori_in_shs='for i in posh yash dash bash mksh ash toysh zsh' \
fori_in_shs:='fori_in_shs ; {{ $i -c ":" ; }}' \
\
tt='$ "time tt-split"' \
tt-split='\tt-split -showwpm -noskip -oneshot' \
tt-noraw='time \tt -showwpm -noskip -oneshot' \
\
reboot-firmware-setup='systemctl reboot --firmware-setup' reboot-toefi=reboot-firmware-setup \
\
startplasma-wayland='SHLVL= \startplasma-wayland' \
byobu='SHLVL= \byobu' \
startx='SHLVL= startx ~/.config/xorg-xinit/xinitrc' \
\
wget='\wget -c -t 5' \
dd='\dd status=progress' \
zsh='zsh --no-rcs' \
gparted=/usr/lib/gparted/gpartedbin \
l.='l -d .*' \
;

if command. exa; then
alias \
	ls='exa -aF' \
	ll='exa -alF --git --time-style iso --group-directories-first -g' \
	l='exa -alF --git --time-style iso --group-directories-first -a' \
	llT='exa -alF --time-style iso --group-directories-first -Th' \
	llT0='llT --level 0' llT1='llT --level 1' llT2='llT --level 2' llT3='llT --level 3' llT4='llT --level 4' llT5='llT --level 5' \
	lg='ll -g' \
	llg='lg' \
;
else
alias \
	ls='\ls --color=auto' \
	l='ls -AF' \
	ll='ls -al --group-directories-first' \
;
fi

return

# fix gparted not alowing not root user: (todo-one-day: make macman hook to auto fix it)
#@#alias gparted=/usr/lib/gparted/gpartedbin

## use login shell for dash and (zsh FIX):
#command. -- -dash && alias dash='PATH=~/bin/_shell-link:${PATH:?} -dash' 

# alias zsh='PATH=~/tmp/_-is/dash:$PATH -zsh'
# zsh !!! .... , NO CONFIG NO PROBLEM WITH MISSING FK CONFIG:
#@#alias zsh='zsh --no-rcs'

# command. ???->mac-specufic-command && 
#@alias dd='\dd status=progress'
# dd status # not supported in darwin


# .homedir to be clean
# note: [ line that should be in ~/B/_home.export~not_needed~, but its just 1 lie: ]
#@#alias startx='SHLVL= startx ~/.config/xorg-xinit/xinitrc'





# command. rmtrash && rmt=
# todo? alias unvi un-vi to unalias thouse?

# alias our_olwn='777' -> never used \




# alias xargs='\xargs ' x='x ' 
### NOTE: sudo='\sudo ' is from ./_env , xargs is from ./xargs


# alias mount-grep='mount | grep'
# alias mount-grep-pwd='(mount | grep -o "$PWD[^ ]*")' # 
# alias gmount.pwd='(mount | grep -o "$PWD[^ ]*")'

