#!/ hint/sh

case ${USER-}:${HOSTNAME-} in
arcowo:kpc)
	alias dotfiles-env='GIT_DIR=/^/\ https://github.com/denisde4ev/dotfiles.git ' dotfiles='dotfiles-env git'
	;;

# todo:
#/data/data/com.termux/files/home:dumpling)
#	alias dotfiles='git --git-dir=/^/_/git-branch:master/\ https://github.com/denisde4ev/dotfiles.git'
#	;;
#/root:artix)
#	alias dotfiles='git --git-dir=/^/_/git-branch:master/\ https://github.com/denisde4ev/dotfiles.git'
#	;;
esac
