#! /hint/sh

# $EDITOR comes from ./_env

case ${EDITOR+x} in '')
	i{
	for i in micro nano vim vi ed edit less most more cat CAT; do
		command. "$EDITOR" || continue
		case $EDITOR in
			ed|less|most|more|cat|CAT) puts "warn: EDITOR=$EDITOR" >&2; break;; # warn when using ed/pager/cat for editor
			# how to do iiit ??? ### read) alias edit="CAT"
			# CAT is from ~/B/_loadable or bin/CAT (loaded after this file - reason alphabetical order)
		esac
		break

	done
	}i
esac

case ${EDITOR-} in micro)
	if command. micro-pre-edit-diff; then
		EDITOR=micro-pre-edit-diff;
	fi
esac


case $(command -v com-which) in
	*/*)
		# NOTE: facky way to using internal alias to expand another alais in middle of the line..
		alias \
			__com-which-c='com-which -c ' \
			\
			e.which='__com-which-c edit' \
			e.which.alias='alias | __com-which-c edit --read-alias' \
		;
	;;
	*)
		alias e.which='com-which -c "${EDITOR:-vi}"' # note this fn comes from ~/B/_loadable/
	;;
esac

# [  "${BASH:-}" != '' ] || {
	# alias e.which.alias='alias | com-which -c edit --read-alias ' # TODO: test it
	# alias e.which\!=e.which.alias  e.cmd,which+=e.which.alias # naver used

# some common files for edit:
alias \
edit='"${EDITOR:?}"' \
e.trizen.conf='edit ~/.config/trizen/trizen.conf' \
e.pacman.conf='edit /etc/pacman.conf' e.pacman='e.pacman.conf' \
e.pacman_mirrorlist='edit /etc/pacman.d/mirrorlist' \
e.resolv='edit /etc/resolv.conf' \
e.known_hosts='edit ~/.ssh/known_hosts' \
e.ssh_config='edit ~/.ssh/config' \
e.TODO='edit ~/0/TODO' \
e.doas='vidoas' vidoas='\doas "${EDITOR:-vi}" /etc/doas.conf' \
e.16='e -encoding=utf-16' \
\
\
ew=e.which e=edit \
;
#	c.open='cout | x open' \ # never used
