#!/ /hint/sh

__load_loadable() {
	unalias "$1"

	case $1 in
		*/* ) . "$1";;
		*) . ~/B/_loadable/"$1".sh;;
	esac

	local i;i=$1; shift
	eval "$i ${@:+"\"\${@}\""}"  #"
}


for i in YN_confirm + sh_require; do
	alias "$i"="__load_loadable $i"
done
