#!/hint/sh

# --null --no-run-if-empty --delimiter
# -0     -r                -d         

alias \
	xo='(x% open %)'\
	\
	xargs='\xargs -d \\n -r' \
	x='xargs ' \
	Zin-xargs='xargs -0 ' \
	Zxargs='Zin-xargs ' \
	Zx='Zxargs ' \
	\
	x%='x -I% ' \
	Zx%='Zx -I% ' \

