#!/ /hint/sh

( # isolate in subshell (...)
	i=$(shuf_1 ~/B/_fetch/[!_.]*[!%~])

	# if this exit, next case-in lines will not be executed
	. "$i"

	case ${i##*/} in 16|color-eudaldgr|fetchName|_fetch.sh|%nofetch) false; esac
) || PS1-ash
