#! /hint/bash
# only in 'current' shell can check for the size of the terminal ? todo: check if is true

shopt -s checkwinsize

printf '█%.0s' `seq 1 $(( LINES * COLUMNS ))` | lolcat
sleep .69 # enjoy to the fullscneen before printing the prompt PS1
