#! /hint/sh

alias com-which=_fallbackfn__com_which;

_fallbackfn__com_which(){(
	set -feu
	OPTIND=1;getopts c: _;x=$OPTARG
	! getopts "" _;shift $((OPTIND-1))  # expected non arg or "--"
	IFS=${NEW_LINE?};
	set -- $(fori{{ which -- "$i"||puts "$i";}})
	unset IFS; eval " ${x:?} ${@+"\"\$@\""}" #"
)}
