#! /hint/sh

i{
for i in ~/B/_fallback/[a-z_]*[!%~]; do
	command. "${i##*/}" || {
		puts "note: using fallback for command '$i'"
		. "$i"
	}

##	command. "${i##*/}"
##	echo command. "${i##*/}" $?
done
}i
