#! /hint/sh

# at least enshure that var is not defined when using local, pls dont ever use `local i=1` or `local i=$(ls)`
local() {
	# when no args returns 0, as expected
	while case $# in 0) return 0; esac; done
		eval \
			"case \"\${${1%%=*}+x}\" in" \
				"x) return 1;;" \
			"esac" \
		&& \
		case $1 in
			#*=*) eval ": \"\${${1%%=*}=$(quote "${1#*=}")}\"";;
			*=*) eval ": \"\${${1%%=*}=\"\${1##*=}\"}\"";;
		esac \
		&& \
		shift
	done
};

# DONT: `unset`,
# REASON: may cause bug in uper scope function by unsetting it.
# scripts should detect exit code from the 'local()' function!
