#! /hint/sh

alias \
+=_plus_ \
'cd+'='_cd_plus' \
'cd++'='_cd_plusparents' \
'cd..'=_cd__ \
'..'=_cd__ \
'cd.which'='cd.. which-ll' \
'cd.'=_cd_dot \
\
song=_song \
pwd=_pwd_ \
\
+='_plus_' \
ll.parents='_ll_parents' \
set-x='_set_x' \
'type=_type_' '?=_type_' '??=_type_ -a' \
;
