#! /hint/sh

__load_loadable() {
	case $BASH_SUBSHELL in
		0|'') ;;
		*) # bash sub process!
			printf %s\\n >&2 "warning: fn __load_loadable called in BASH_SUBSHELL='$BASH_SUBSHELL', args: $*"
		;;
	esac

	unalias "$1" 2>/dev/null || {
		"$@"
		return
	}

	if [ -e "$B"/_loadable/"$1"."$sh_is" ]; then
		. "$B"/_loadable/"$1"."$sh_is"
	elif case "$sh_is" in "$sh_is_") false;; *) [ -e "$B"/_loadable/"$1"."$sh_is_" ]; esac; then
		. "$B"/_loadable/"$1"."$sh_is_"
	else
		. "$B"/_loadable/"$1".sh
	fi

	"$@"
}


# TODO: separate CD and cd.. fns

# LOADABLE-aliases:
#mv=_mv_or_editorrename_ \ # aliased 'mv -vi' in $B/a
alias \
ll-test=ll_test \
git='_git__' \
find=_find_ \
+=_plus_ \
'cd+'='_cd_plus' \
'cd++'='_cd_plusparents' \
CD='cd..' \
'cd..'=_cd__ \
'..'=_cd__ \
'cd.which'='cd.. which-ll' \
'cd.'=_cd_dot \
\
song=_song \
pwd=_pwd_ \
\
+='_plus_' \
ll.parents='_ll_parents' \
set-x='_set_x' \
'type=_type_' '?=_type_' '??=_type_ -a' \
e.loadable='_edit_loadable ' \
;
# ?- is from "$B"/a


unset-unseted-i
for i in "$B"/_loadable/[a-zA-Z0-9_]*.sh ${sh_is_bash+"$B"/_loadable/[a-zA-Z0-9_]*.bash}; do
	i=${i##*/}
	i=${i%.*}
	alias "$i"="__load_loadable $i"
done
unset-seted-i
